name: Project Board Automation - Pyrsia Development

on:
  issues:
    types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]

env:
  todo: Todo
  done: Done
  in_progress: In Progress
  mvp: MVP
  blocked: Blocked

jobs:
  triage-new-issues:
    runs-on: ubuntu-latest
    if: |
      github.repository_owner == 'pyrsia' &&
      github.event_name == 'issues' &&
      (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: |
            triage
            website
      - name: Move issue to ${{ env.todo }}
        uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          action: add
          status_value: ${{ env.todo }}
          project_id: 3
          organization: pyrsia
          gh_token: ${{ secrets.ORG_ACCESS_TOKEN }}
          resource_node_id: ${{ github.event.issue.node_id }}

  in-progress-new-prs:
    runs-on: ubuntu-latest
    if: |
      github.repository_owner == 'pyrsia' &&
      github.event_name == 'pull_request_target' &&
      (github.event.action == 'opened' || github.event.action == 'reopened')
    steps:
      - uses: toshimaru/auto-author-assign@v1.5.1
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: website
      - uses: leonsteinhaeuser/project-beta-automations@v1.3.0
        with:
          status_value: ${{ env.done }}
          project_id: 3
          organization: pyrsia
          gh_token: ${{ secrets.ORG_ACCESS_TOKEN }}
          resource_node_id: ${{ github.event.issue.node_id }}