name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  community-health-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: pyrsia/.github
      - name: set custom edit URLs
        shell: python
        run: |
          import os
          for file in os.listdir('.'):
            if file.endswith('.md'):
              new_line = '---\ncustom_edit_url: https://github.com/pyrsia/.github/edit/main/{}\n---\n\n'.format(file)
              with open(file, 'r+') as file:
                content = file.read()
                file.seek(0)
                file.write(new_line + content)
      - uses: actions/upload-artifact@v3
        with:
          name: health-files
          path: '*.md'
  devs-hub-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: pyrsia/pyrsia
      - name: set custom edit URLs
        shell: python
        run: |
          import glob
          for file in glob.iglob('docs/**/*.md', recursive=True):
            new_line = '---\ncustom_edit_url: https://github.com/pyrsia/pyrsia/edit/main/{}\n---\n\n'.format(file)
            with open(file, 'r+') as file:
              content = file.read()
              file.seek(0)
              file.write(new_line + content)
      - uses: actions/upload-artifact@v3
        with:
          name: devs-files
          path: 'docs/**/*.md'
  deploy:
    needs: [community-health-files, devs-hub-files]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: npm
      - uses: actions/download-artifact@v3
        with:
          name: health-files
          path: docs/get_involved
      - uses: actions/download-artifact@v3
        with:
          name: devs-files
          path: docs/get_involved
      - run: |
          npm ci
          npm run build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: true
          cname: pyrsia.io
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
